apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-access
  namespace: kube-system
subjects:
- kind: User
  name: u-6wbgglf6an
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sealed-secrets-controller
  apiGroup: rbac.authorization.k8s.io
